### ISSUE TITLE
Training of swift_yolo_tiny_1xb16_300e_coco gives "list index out of range"

### ISSUE THREAD

**Issue by sbocconi** [Seeed-Studio/ModelAssistant#178]
**Describe the bug**
When training with config `swift_yolo_tiny_1xb16_300e_coco` after 5 epochs I get `IndexError: list index out of range`

**Environment**
Environment you use when bug appears:

1. Python version: 3.10
2. PyTorch Version: torch==2.0.1
3. MMCV Version: 2.0.1
4. EdgeLab Version: na
5. Code you run: 
`python tools/train.py configs/swift_yolo/swift_yolo_tiny_1xb16_300e_coco.py --cfg-options data_root=datasets/digital_meter/ epochs=10`
6. The detailed error
```
Traceback (most recent call last):
  File "/Users/SB/Projects/Software/Zephyros/Courses/Microcontrollers/ModelAssistant/tools/train.py", line 226, in <module>
    main()
  File "/Users/SB/Projects/Software/Zephyros/Courses/Microcontrollers/ModelAssistant/tools/train.py", line 221, in main
    runner.train()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmengine/runner/loops.py", line 374, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmengine/evaluator/metric.py", line 133, in evaluate
    _metrics = self.compute_metrics(results)  # type: ignore
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmdet/evaluation/metrics/coco_metric.py", line 419, in compute_metrics
    result_files = self.results2json(preds, outfile_prefix)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmdet/evaluation/metrics/coco_metric.py", line 239, in results2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range
```

**Additional context**
Running on  Mac M2, torch cpu-only, mmcv compiled from source

**Comment by MILK-BIOS** [comment]
Hi @sbocconi!
1.  You need to check your config file `configs/swift_yolo/swift_yolo_tiny_1xb16_300e_coco.py`   
2.  Then try to match the `num_classes` with the dataset classes. (It is expeced to be _11_ in digital_meter dataset)

If the error is still there, please contact us. Thank you!
