### ISSUE TITLE
Verifying TFlite export of fomo_mobnetv2_0.35_x8_abl_coco fails with IndexError

### ISSUE THREAD

**Issue by sbocconi** [Seeed-Studio/ModelAssistant#186]
**Describe the bug**
Trying to verify the TFlite export of fomo_mobnetv2_0.35_x8_abl_coco fails with:
```
IndexError: index 6 is out of bounds for dimension 2 with size 3
```
This is strange because the model had been verified after training without problems.

**Environment**
Environment you use when bug appears:

1. Python version: 3.10
2. PyTorch Version: torch==2.0.1
3. MMCV Version: 2.0.1
4. EdgeLab Version: na
5. Code you run
` python3 tools/inference.py configs/fomo/fomo_mobnetv2_0.35_x8_abl_coco.py "$(cat work_dirs/fomo_mobnetv2_0.35_x8_abl_coco/last_checkpoint | sed -e 's/.pth/_int8.tflite/g')" --show --cfg-options data_root="datasets/coco_mask" `
6. The detailed error
```
Traceback (most recent call last):
  File "/Users/SB/Projects/Software/Zephyros/Courses/Microcontrollers/ModelAssistant/tools/inference.py", line 352, in <module>
    main()
  File "/Users/SB/Projects/Software/Zephyros/Courses/Microcontrollers/ModelAssistant/tools/inference.py", line 348, in main
    runner.test()
  File "/Users/SB/Projects/Software/Zephyros/Courses/Microcontrollers/ModelAssistant/sscma/utils/inference.py", line 397, in test
    self.evaluator.process(data_batch=data, data_samples=data['data_samples'])
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmengine/evaluator/evaluator.py", line 60, in process
    metric.process(data_batch, _data_samples)
  File "/Users/SB/Projects/Software/Zephyros/Courses/Microcontrollers/ModelAssistant/sscma/evaluation/fomo_metric.py", line 74, in process
    tp, fp, fn = multi_apply(self.compute_ftp, preds, target)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmdet/models/utils/misc.py", line 219, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/Users/SB/Projects/Software/Zephyros/Courses/Microcontrollers/ModelAssistant/sscma/evaluation/fomo_metric.py", line 44, in compute_ftp
    if site in preds_index and preds_max[site.chunk(3)] == target_max[ti.chunk(3)]:
IndexError: index 6 is out of bounds for dimension 2 with size 3
```

**Additional context**

Running on Mac M2, torch cpu-only, mmcv compiled from source

**Comment by MILK-BIOS** [comment]
Hi @sbocconi! Thanks for your issue! This problem is mainly caused by a unexpectational permute operation of model's prediction. We checked our code and update it. Please try the latest one.

**Comment by sbocconi** [comment]
Hi @MILK-BIOS , now I get another error when verifying the trained model with:

`export OMP_NUM_THREADS=1 && python tools/train.py configs/fomo/fomo_mobnetv2_0.35_x8_abl_coco.py --cfg-options data_root=datasets/coco_mask epochs=5 ` :

```
Traceback (most recent call last):
  File "/Users/SB/Projects/Software/Zephyros/Courses/Microcontrollers/ModelAssistant/tools/train.py", line 226, in <module>
    main()
  File "/Users/SB/Projects/Software/Zephyros/Courses/Microcontrollers/ModelAssistant/tools/train.py", line 221, in main
    runner.train()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmengine/runner/loops.py", line 371, in run
    self.run_iter(idx, data_batch)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmengine/runner/loops.py", line 392, in run_iter
    self.evaluator.process(data_samples=outputs, data_batch=data_batch)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmengine/evaluator/evaluator.py", line 60, in process
    metric.process(data_batch, _data_samples)
  File "/Users/SB/Projects/Software/Zephyros/Courses/Microcontrollers/ModelAssistant/sscma/evaluation/fomo_metric.py", line 74, in process
    tp, fp, fn = multi_apply(self.compute_ftp, preds, target)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/mmdet/models/utils/misc.py", line 219, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/Users/SB/Projects/Software/Zephyros/Courses/Microcontrollers/ModelAssistant/sscma/evaluation/fomo_metric.py", line 48, in compute_ftp
    confusion = confusion_matrix(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 319, in confusion_matrix
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 85, in _check_targets
    check_consistent_length(y_true, y_pred)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sscma/lib/python3.10/site-packages/sklearn/utils/validation.py", line 457, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [144, 36]
```

**Comment by MILK-BIOS** [comment]
Hi @sbocconi, We Fixed the bug now! Please try it. And if you meet another problem, please contact us!

**Comment by sbocconi** [comment]
This works, thanks!
