### ISSUE TITLE
推理模型如何查看模型的输出，可视化的结果在哪里找？如何输入单张图片并获取box

### ISSUE THREAD

**Issue by woshing700** [Seeed-Studio/ModelAssistant#231]
## 我想查看模型检测结果的可视化，但是将out_dir参数指定目录时，推理代码报错！
我想请问如何将推理结果可视化并保存？

Traceback (most recent call last):
  File "/usr/local/miniconda3/bin/sscma.inference", line 8, in <module>
    sys.exit(main())
  File "/hy-tmp/ModelAssistant/sscma/tools/inference.py", line 286, in main
    runner = Runner.from_cfg(cfg)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 442, in __init__
    self.register_hooks(default_hooks, custom_hooks)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1992, in register_hooks
    self.register_default_hooks(default_hooks)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1966, in register_default_hooks
    self.register_hook(hook)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1877, in register_hook
    hook_obj = HOOKS.build(hook)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'out_dir'

**Comment by baorepo** [comment]
I see that you have not responded for a long time, I will close this issue first, if you have new developments, we will open this issue.
